image: samueldebruyn/debian-git

pipelines:
  default:
    - step:
        script:
          - apt-get update
          - apt-get -qq install git-ftp
          - git ftp init
          - ls -la
          - git ftp push --user $FTP_USERNAME --passwd $FTP_PASSWORD ftp://deribanov.com/
