image: samueldebruyn/debian-git

pipelines:
  default:
    - step:
        script:
          - apt-get update
          - apt-get -qq install git-ftp
          - apt-get install zip unzip
          - ls -la
          - zip -r dotfiles_`date`.zip ./
          - git ftp init -vv  --user $FTP_USERNAME --passwd $FTP_PASSWORD ftp://deribanov.com/
