image: samueldebruyn/debian-git

pipelines:
  default:
    - step:
        script:
          - apt-get update
          - apt-get -qq install git-ftp
          - apt-get install zip unzip
          - rm -rf dotfiles.zip
          - zip -r dotfiles.zip ./
          - ls -la
#          - git ftp init -vv  --user $FTP_USERNAME --passwd $FTP_PASSWORD ftp://deribanov.com/
          - curl -T dotfiles.zip ftp://deribanov.com/ --user $FTP_USERNAME:$FTP_PASSWORD

